#!/bin/bash

# Script to automate building the source files and automate our tests/plotting

# Where to redirect build messages
BUILD_OUTPUT="/dev/null"
#BUILD_OUTPUT=/dev/stdout

PACKAGE_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )/.."

SRC_DIR="$PACKAGE_DIR/src"
BUILD_DIR="$PACKAGE_DIR/build"
DATA_FILES="$PACKAGE_DIR/data"
PLOT_FILES="$PACKAGE_DIR/plotting"
EXE="MatrixMultiplication"


echo "*******************************************" > $BUILD_OUTPUT
echo "          Recompiling files                " > $BUILD_OUTPUT
echo "*******************************************" > $BUILD_OUTPUT
make -C $SRC_DIR > $BUILD_OUTPUT

# overwrite old files with new header
echo "num_threads,square_sizes,time_elapsed" > $DATA_FILES/times.csv

NUM_THREADS=(1 2 4 8 16 32 64 128 256 512)
for thread_num in ${NUM_THREADS[@]}
do
    MATRIX_SIZE=(1 10 100 500 1000 3000)
    for size in ${MATRIX_SIZE[@]}
    do
        TIME_OUTPUT=$($BUILD_DIR/$EXE -M $size -N $size -P $size -n $thread_num -p 1)
        echo "$thread_num,$size,$TIME_OUTPUT" >>  $DATA_FILES/times.csv
    done
done

#python3 $PACKAGE_DIR/scripting/plot_data.py
